# Generated by Django 4.2.5 on 2023-10-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(choices=[('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4')], max_length=2)),
                ('model', models.CharField(choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('R4', 'R4')], max_length=2)),
                ('name', models.CharField(choices=[('light', 'Light'), ('edition', 'Edition'), ('pro', 'Pro')], default='', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
